server:
  port: 8085

spring:
  application:
    name: debit-card-service
  data:
    mongodb:
      auto-index-creation: true
  mongodb:
    uri: mongodb://localhost:27017/debit_card_db

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

logging:
  level:
    com.debit.card.service: DEBUG