server:
  port: 9001

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/api/v1/auth/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: authServiceCB
                    fallbackUri: forward:/fallback/auth
                - name: Retry
                  args:
                    retries: 3
                    statuses: INTERNAL_SERVER_ERROR, SERVICE_UNAVAILABLE
                    methods: GET,POST,PUT,DELETE,PATCH

            - id: client-service
              uri: lb://CLIENT-SERVICE
              predicates:
                - Path=/api/v1/clients/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: clientServiceCB
                    fallbackUri: forward:/fallback/client
                - name: Retry
                  args:
                    retries: 3
                    statuses: INTERNAL_SERVER_ERROR, SERVICE_UNAVAILABLE
                    methods: GET,POST,PUT,DELETE,PATCH

            - id: account-service
              uri: lb://ACCOUNT-SERVICE
              predicates:
                - Path=/api/v1/accounts/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: accountServiceCB
                    fallbackUri: forward:/fallback/account
                - name: Retry
                  args:
                    retries: 3
                    statuses: INTERNAL_SERVER_ERROR, SERVICE_UNAVAILABLE
                    methods: GET,POST,PUT,DELETE,PATCH

            - id: credit-service
              uri: lb://CREDIT-SERVICE
              predicates:
                - Path=/api/v1/credits/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: creditServiceCB
                    fallbackUri: forward:/fallback/credit
                - name: Retry
                  args:
                    retries: 3
                    statuses: INTERNAL_SERVER_ERROR, SERVICE_UNAVAILABLE
                    methods: GET,POST,PUT,DELETE,PATCH

            - id: transaction-service
              uri: lb://TRANSACTION-SERVICE
              predicates:
                - Path=/api/v1/transactions/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: transactionServiceCB
                    fallbackUri: forward:/fallback/transaction
                - name: Retry
                  args:
                    retries: 3
                    statuses: INTERNAL_SERVER_ERROR, SERVICE_UNAVAILABLE
                    methods: GET,POST,PUT,DELETE,PATCH
            - id: debit-card-service
              uri: lb://DEBIT-CARD-SERVICE
              predicates:
                - Path=/api/v1/debit-cards/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: debitCardServiceCB
                    fallbackUri: forward:/fallback/debit-card
                - name: Retry
                  args:
                    retries: 3
                    statuses: INTERNAL_SERVER_ERROR, SERVICE_UNAVAILABLE
                    methods: GET,POST,PUT,DELETE,PATCH

            - id: yanki-service
              uri: lb://YANKI-SERVICE
              predicates:
                - Path=/api/v1/yanki/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: yankiServiceCB
                    fallbackUri: forward:/fallback/yanki
                - name: Retry
                  args:
                    retries: 3
                    statuses: INTERNAL_SERVER_ERROR, SERVICE_UNAVAILABLE
                    methods: GET,POST,PUT,DELETE,PATCH

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

# Resilience4j config
resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000ms
        permitted-number-of-calls-in-half-open-state: 5
        register-health-indicator: true
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 2s
    instances:
      authServiceCB:
        base-config: default
      clientServiceCB:
        base-config: default
      accountServiceCB:
        base-config: default
      creditServiceCB:
        base-config: default
      transactionServiceCB:
        base-config: default
      debitCardServiceCB:
        base-config: default
      yankiServiceCB:
        base-config: default

  timelimiter:
    configs:
      default:
        timeout-duration: 2s

  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration: 1s
        retry-exceptions:
          - java.util.concurrent.TimeoutException
          - org.springframework.web.client.HttpServerErrorException

management:
  endpoints:
    web:
      exposure:
        include: health, info, circuitbreakers, circuitbreakerevents
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    io.github.resilience4j: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG

# JWT Configuration
app:
  jwt:
    secret: ${JWT_SECRET:miClaveSecretaMuyLargaParaFirmaDeJWT256BitsQueDebeTenerAlMenos32Caracteres}
    expirationMs: 86400000