server:
  port: 8080

spring:
  application:
    name: client-service
  mongodb:
    uri: mongodb://localhost:27017/client_db

logging:
  level:
    root: INFO
    com.client.service: INFO

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    prefer-ip-address: true