server:
  port: 8001
spring:
  application:
    name: account-service
  mongodb:
    uri: mongodb://localhost:27017/account_db
  cloud:
    stream:
      bindings:
        yankiPaymentRequestConsumer-in-0:
          destination: yanki-payment-requests
          group: account-service-group
        yankiPaymentResponseProducer-out-0:
          destination: yanki-payment-responses
      kafka:
        binder:
          brokers: localhost:9092
          auto-create-topics: true

logging:
  level:
    root: INFO
    com.account.service: INFO

client-service:
  url: http://localhost:8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    prefer-ip-address: true